CREATE TABLE tb_genres (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE tb_books (
    id VARCHAR(36) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    description CLOB,
    published_year INT,
    publisher VARCHAR(100),
    page_count INT,
    id_google VARCHAR(50) UNIQUE,
    created_at TIMESTAMP
);

CREATE TABLE tb_books_genres (
    book_id VARCHAR(36) NOT NULL,
    genre_id INT NOT NULL,
    PRIMARY KEY (book_id, genre_id),
    FOREIGN KEY (book_id) REFERENCES tb_books(id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES tb_genres(id) ON DELETE CASCADE
);

CREATE TABLE tb_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id VARCHAR(36) NOT NULL UNIQUE,
    start_date DATE,
    end_date DATE,
    status VARCHAR(20) CHECK (status IN ('READ', 'READING', 'WANT_TO_READ', 'ABANDONED')) NOT NULL,
    rating DOUBLE CHECK (rating >= 0 AND rating <= 5),
    CONSTRAINT fk_reading_book FOREIGN KEY (book_id) REFERENCES tb_books(id) ON DELETE CASCADE
);

CREATE TABLE tb_preferences (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_id INT NOT NULL UNIQUE,
    rating_sum DOUBLE NOT NULL DEFAULT 0,
    rating_count INT NOT NULL DEFAULT 0,
    avg_rating DOUBLE NOT NULL,
    FOREIGN KEY (genre_id) REFERENCES tb_genres(id) ON DELETE CASCADE
);
